
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyiyuqpcxjwxingjgpiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5aXl1cXBjeGp3eGluZ2pncGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzMwNDYsImV4cCI6MjA1NTQ0OTA0Nn0.oaOKB7e6oSTTYIgQHGSsM2N6L1kdVdf3_jT7MXVfSUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
